export * from './append'
export * from './pattern'
export * from './prepend'
export * from './removeChar'
export * from './replace'
export * from './s2a'
export * from './s2o'
export * from './template'
